### ISSUE TITLE
No PAM

### ISSUE THREAD

**Issue by ghost** [maximilianh/crisporWebsite#1]
Hi

I was wondering if CRISPOR would work if no PAM site was needed as in the case of the N. gregoryi http://www.nature.com/nbt/journal/v34/n7/full/nbt.3547.html

Thank you.

**Comment by maximilianh** [comment]
Nice idea! Yes. Well, it may overflow the sequence view a little. Let us discuss this internally to see how it could look...

**Comment by maximilianh** [comment]
Looking into it, I stumbled over this post: 
https://medium.com/@GaetanBurgio/my-experience-with-natronobacterium-gregoryi-argonaute-ngago-3ed8909b410c#.g8ihowj36

**Comment by maximilianh** [comment]
I think N. gregoryi is not a current priority to support. If you have additional information and you think I should add support for it, please do not hesitate to post it into this ticket. If you have any other suggestions, do not hesitate to contact me or open another issue. Thanks!
