### ISSUE TITLE
Error while downloading hg38 data

### ISSUE THREAD

**Issue by asgarhussain** [maximilianh/crisporWebsite#14]
I am getting following error when I tried to download hg38 database using this command 

sudo ./crisprAddGenome ucsc hg38

==== Downloading ensembl transcripts to gene name table ==== 
INFO:root:Running: wget http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ensemblToGeneName.txt.gz -O - | zcat > /tmp/hg38/hg38.ensemblToGeneName.txt
--2018-07-27 17:41:30--  http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ensemblToGeneName.txt.gz
Resolving hgdownload.cse.ucsc.edu (hgdownload.cse.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.cse.ucsc.edu (hgdownload.cse.ucsc.edu)|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-27 17:41:32 ERROR 404: Not Found.

gzip: stdin: unexpected end of file
Could not run command wget http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/ensemblToGeneName.txt.gz -O - | zcat > /tmp/hg38/hg38.ensemblToGeneName.txt

UCSC has removed this file from URL.

**Comment by maximilianh** [comment]
Actually, for hg38, you wouldn't use this command at all. You would use the
other tool, crisprGetGenome
 (or was it crisprDownloadGenome?). Anyhow, just use the other script. :-)

**Comment by asgarhussain** [comment]
Thanks

**Comment by maximilianh** [comment]
did it work?
