### ISSUE TITLE
Errors while running crispor.py script (AttributeError: 'NoneType' object has no attribute 'startswith')

### ISSUE THREAD

**Issue by asgarhussain** [maximilianh/crisporWebsite#15]
I am getting following error at end of the job 
Traceback (most recent call last):
  File "crispor.py", line 7159, in <module>
    main()
  File "crispor.py", line 7157, in main
    mainCommandLine()
  File "crispor.py", line 7021, in mainCommandLine
    mergeGuideInfo(seq, startDict, pamPat, otMatches, position, effScores)
  File "crispor.py", line 1856, in mergeGuideInfo
    makePosList(org, pamMatches, guideSeqFull, pamPat, inputPos)
  File "crispor.py", line 1414, in makePosList
    alnHtml, hasLast12Mm = makeAlnStr(org, guideSeq, otSeq, pam, mitScore, cfdScore, posStr, dist)
  File "crispor.py", line 1298, in makeAlnStr
    if org.startswith("mm") or org.startswith("hg") or org.startswith("rn"):
AttributeError: 'NoneType' object has no attribute 'startswith'

Although, with sample genome file everything is running smoothly.

**Comment by maximilianh** [comment]
Which command did you run?

**Comment by maximilianh** [comment]
What was the input?

**Comment by asgarhussain** [comment]
I executed following command 
python2.7 crispor.py hg38  sampleFiles/mine/rag1a.fa  sampleFiles/rag1a.tsv  -o sampleFiles/rag1a.off.tsv

input file 'rag1a.fa' look like this
>hg38_dna
TCTCAGGTACCTCAGCCAGCATGGCAGCCTCTTTCCCACCCACCTTGGGACTCAGTTCTGCCCCAGATGAAATT

**Comment by maximilianh** [comment]
Oh darn, this is my fault! Sorry! One second.

**Comment by maximilianh** [comment]
OK, can you do a git pull and check if this is solved now? I must have
introduced this bug when adding the off-target distance to the web
interface a few days ago. Thanks for reporting it!

On Mon, Jul 30, 2018 at 2:31 PM, Maximilian Haeussler <maximilianh@gmail.com

**Comment by asgarhussain** [comment]
Thanks. It is working now.

**Comment by maximilianh** [comment]
Against, thank you for reporting this and let me know if you have any suggestions on the software.
