### ISSUE TITLE
a few suggestions to facilitate local installation and execution

### ISSUE THREAD

**Issue by loire** [maximilianh/crisporWebsite#16]
Hi, 
I'm currently using crispor, thanks for sharing the code. 

I cloned the repo the 17 septembre 2018 (commit  2d08207)

I ran through a few hurdles during installation/execution (despite a nice README) which I overcame this way:
I used a virtual environment with python 2.7.7, it helped to install the correct versions of the dependencies. 
But it can broke the execution of some of the utils tools because of inconsistencies between python 3 (default on my system) and the virtual 2.7 
Using #!usr/bin/env python as shebang in all scripts saved the day. I think you could replace them systematically.

BedBetween and bedOverlaperge raised an indentation error, I corrected them in my editor.

in crisprAddGenome, line 991, before invoking ./makeGenomeInfo, the script tries to cd in "/data/www/crispor" which is not necessarly an existing path nor the correct one depending on where the script is stored. 
Hope it helps :)

Thanks again, will let you know how it runs

**Comment by maximilianh** [comment]
Hi, thanks for the feedback! What is your system? Why is Python3 the
default?

Shouldn't I be explicit in the shebang and specify python2 when it's
python2 ?

hmm... very strange... bedBetween and bedOverlapMerge do not raise an
indentation error on my system. I don't understand how this is possible.
I've been using them for 5-6 years.

**Comment by loire** [comment]
archlinux currently ships with python3, but I reckon it's a bit specific. 
I was surprised by the indent too, I corrected them before switching the python version so it may have been the cause... 

I also added multithreading to the bwa steps. Not a big gain, but since I'm trying to find guides on a 300kb sequence space, it helps a little.

**Comment by maximilianh** [comment]
BWA is not the slowdown, it's twoBitToFa. You can replace it with bedtools,
then the program is 10 times faster or more. Where twoBitToFa is called,
there is a line that you can uncomment to make this work.

**Comment by loire** [comment]
oh cool, I will give it a try  

This part ? 
what's the xxx part after the pipe ? 
```
2954     # EXTRACTION OF SEQUENCES + ANNOTATION
2955     # twoBitToFa was 15x slower than python's twobitreader, after markd's fix it should be OK
2956     # Hiram says this is faster:
2957     # bedtools getfasta -s -name -fi %(genome)s.fa -bed %(matchesBedFname)s -fo /dev/stdout  | xxx
2958     cmd = "$BIN/twoBitToFa %(genomeDir)s/%(genome)s/%(genome)s.2bit stdout -bed=%(matchesBedFname)s | $SCRIPT/filterFaToBed %(faFname)s %(pam)s %(altPats)s %(altPamMinScore)s %(maxOcc)d > %(filtMatchesBedFname)s" % locals()
2959     #cmd = "$SCRIPT/twoBitToFaPython %(genomeDir)s/%(genome)s/%(genome)s.2bit %(matchesBedFname)s | $SCRIPT/filterFaToBed %(faFname)s %(pam)s %(altPats)s %(altPamMinScore)s %(maxOcc)d > %(filtMatchesBedFname)s" % locals()
2960     runCmd(cmd)
```

**Comment by maximilianh** [comment]
You have to replace this part:

$BIN/twoBitToFa %(genomeDir)s/%(genome)s/%(genome)s.2bit stdout
-bed=%(matchesBedFname)s


with

bedtools getfasta -s -name -fi %(genome)s.fa -bed %(matchesBedFname)s
-fo /dev/stdout

Kudos to @nullmodel for finding this command. I knew that a speedup was
possible, but didn't realize that bedtools is exactly the perfect command
for this.

To make this really fast, put your genomes onto /dev/shm (you can make the
"genomes" directory a symlink).

It's been on my todo list for years to increase the speed, but since we
have flashfry now, it was never urgent.

**Comment by loire** [comment]
oh. Didn't knew about it - been requested to run crispor, but if you feel it's a better alternative for long regions I may give it a try

just fyi, the script stopped here: 
```
[main] CMD: /home/loire/work/Celia/crisporWebsite/bin/Linux/bwa samse -n 60000 ./genomes/GCF_002204515.2/GCF_002204515.2.fa TEMP/QN8epiv8tt5beHtWx7d3.sa TEMP/QN8epiv8tt5beHtWx7d3.fa                                                          
[main] Real time: 1326.729 sec; CPU: 626.514 sec                                                                                                                                                                                               
Unable to flush stdout: Broken pipe                                                                                                                                                                                                            
ERROR:root:Error: could not run command set -o pipefail; /home/loire/work/Celia/crisporWebsite/bin/Linux/bwa samse -n 60000 ./genomes/GCF_002204515.2/GCF_002204515.2.fa TEMP/QN8epiv8tt5beHtWx7d3.sa TEMP/QN8epiv8tt5beHtWx7d3.fa | ./bin/xa2m
ulti.pl | ./bin/samToBed NGG 20 | sort -k1,1 -k2,2n | /home/loire/work/Celia/crisporWebsite/bin/Linux/bedClip stdin ./genomes/GCF_002204515.2/GCF_002204515.2.sizes stdout >> TEMP/QN8epiv8tt5beHtWx7d3.matches.bed .        
```
Gonna launch the remaining steps manually unless you have a suggestion

**Comment by maximilianh** [comment]
Sorry no idea, I'd run these commands manually to try. I would expect
problems due to your python version.

**Comment by loire** [comment]
I'm still on the samToBed step, once  it's complete I will let you know how it goes so you can close the issue. 
Meanwhile flashfry has already completed the job ;)
Thanks for your time and the suggestion !

**Comment by maximilianh** [comment]
So you'll use flashfry?

**Comment by loire** [comment]
I may use a combination of both: Flashfry was able to process the 300kb chunk easily, got more 20,000 potential guide that I will filter according to my colleagues preference, then use crispor to get the neat additional infos on the locus. 
Fyi, samToBed is still running 10hours later, I think it was the culprit for the broken pipe. 

You may close the issue: My main problem was that crispor is unfortunately unsuitable for such a large genomic segment ! 
Cheers
E.

**Comment by maximilianh** [comment]
Would you be able to share the input sequence region?

I've used crispor on big input regions before, we use it for the whole
genome at UCSC. So it's working in principle, but it's possible that I
modified something with the repeat filtering that broke it recently.

**Comment by loire** [comment]
Sure ! 
https://drive.google.com/file/d/1fk1UIwjEYC5WawsO1LTzDNB3V_lqxL4f/view?usp=sharing
It's a chunk of the Aedes aegypti L5 genome( GCF_002204515.2 on refseq)

**Comment by SeqCrafter** [comment]
I want to know how you annotate each offtarget sequence that whether they fall into an exon, intron or between genes and the closest gene

**Comment by maximilianh** [comment]
@panxiaoguang sorry for the long delay: I annotated using bedOverlap and special segments.bed files. 

Closing this issue now. The user found flashfry to be the better tool for large sequences.
