### ISSUE TITLE
Missing gRNA warnings with command-line CRISPOR

### ISSUE THREAD

**Issue by genya** [maximilianh/crisporWebsite#23]
The CRISPOR website provides warnings of potential problems with gRNA sequences, such as presence of TTTT that terminates transcription from U6 promoters, but I do not see these warnings in the outputs of the command-line version. Is this feature built-in to the command-line version or should the user do his own checks for these problems? Thanks!

**Comment by maximilianh** [comment]
I assume that command line users know what they are doing.

**Comment by genya** [comment]
that makes sense, thanks!
