### ISSUE TITLE
format for custom genome

### ISSUE THREAD

**Issue by tiramisutes** [maximilianh/crisporWebsite#34]
Dear,
I want to add my research genome to crispor. And I noted the example in [Adding a genome](
https://github.com/maximilianh/crisporWebsite#adding-a-genome) section used a repeatMasked genome fasta file. 
My question is why not an original assembled genome. And original assembled genome, hardmasked and softmasked, which is best?

Any help is much appreciated.
Thanks.

Best regards

**Comment by maximilianh** [comment]
softmasked. Crispor needs the normal genome.

The softmasking is useful, e.g. in primer design, we can avoid repeats. As
a general rule, softmasked genomes should be the default everywhere. There
is no loss of information and it's often good to know about repeats.

**Comment by tiramisutes** [comment]
Thanks for your explanation.
