### ISSUE TITLE
Whether the input genome should be repeat masked?

### ISSUE THREAD

**Issue by tiramisutes** [maximilianh/crisporWebsite#41]
Dear,
I want to add a genome in "fasta" mode use `crisprAddGenome fasta` command. 
Then I see the [Adding a genome](https://github.com/maximilianh/crisporWebsite#adding-a-genome), but I want to know whether the fasta genome should be repeated masked?

Thanks.

**Comment by maximilianh** [comment]
No. Please do not repeat mask the genome. It's good to have it soft-masked,
so primer3 can avoid repeats. But you want to know about CRISPR off-targets
in repeats.

Also, it's easier if you send me a genome so I can index it. I can block it
for downloads on the website.
