### ISSUE TITLE
Whether the input sequence can be mRNA sequence when gff3 file is given for a new species genome?

### ISSUE THREAD

**Issue by tiramisutes** [maximilianh/crisporWebsite#43]
Hi,
I have cloned this software locally and want to run for a new species genome. I want to know whether the mRNA sequence not each exon sequence for an mRNA can input when provided a gff annotation file?
 Thanks.

**Comment by maximilianh** [comment]
In many cases, this would mean extremely long input sequences... but yes,
if you remove/increase the input sequence limit you can input all exons.

You cannot input the mRNA. CRISPR is a genome-editing tool. It cannot
modify the places in the mRNA that go over splice junctions.

**Comment by tiramisutes** [comment]
So I'm little troubled by it. All exons are mean mRNA (from start to stop codons, for example  [full length CDS of AT3G47570.1](https://www.arabidopsis.org/servlets/TairObject?type=sequence&id=638475)). If we cannot input the mRNA sequence, what is the purpose of gff3 file that input when adding a genome use `crisprAddGenome` command?

**Comment by maximilianh** [comment]
The purpose of the GFF file is so you can see where the off-targets are. Users care a lot about to know if an off-target is in a gene or not. 

In theory the GFF could be used to pick guides, given a transcript or gene. But I'm not there yet. Maybe in 2-5 years... :-)
