### ISSUE TITLE
Error using rat rn6 genome on local installation

### ISSUE THREAD

**Issue by Lukas-1** [maximilianh/crisporWebsite#54]
I downloaded the [rat rn6 genome](http://crispor.tefor.net/genomes/rn6/) provided on the CRISPOR website, and tried to use it to find off-target locations for gRNAs using a .bed file as an input. This has previously worked for me very well using the hg38anset and mm10 genomes.

However, with the rn6 genome, I get an error:

> python crisporWebsite/crispor.py rn6 Input_for_CRISPOR/input.bed Output_from_CRISPOR/output.tsv -o Output_from_CRISPOR/output_offs.tsv
> Traceback (most recent call last):
>   File "crisporWebsite/crispor.py", line 8482, in <module>
>     main()
>   File "crisporWebsite/crispor.py", line 8479, in main
>     mainCommandLine()
>   File "crisporWebsite/crispor.py", line 8241, in mainCommandLine
>     seqList = getGenomeSeqs(org, regions)
>   File "crisporWebsite/crispor.py", line 6979, in getGenomeSeqs
>     seq = tbf[chrom][start:end]
>   File "/usr/local/lib/python2.7/dist-packages/twobitreader/__init__.py", line 432, in __getitem__
>     return self.get_slice(min_=slice_or_key.start, max_=slice_or_key.stop)
>   File "/usr/local/lib/python2.7/dist-packages/twobitreader/__init__.py", line 517, in get_slice
>     more_bytes=morebytes)
>   File "/usr/local/lib/python2.7/dist-packages/twobitreader/__init__.py", line 158, in longs_to_char_array
>     raise ValueError('array_size must be at least 0')
> **ValueError: array_size must be at least 0**

I haven't been able to figure out what might cause this error... Any help would be much appreciated!

**Comment by Lukas-1** [comment]
Sorry, the error was on my side. I submitted a file that erroneously included a position on chromosome 22, which doesn't exist in the rat genome. This immediately caused the error above. The error isn't very informative, but I guess that's the fault of the twobitreader package...

**Comment by maximilianh** [comment]
Thanks for solving the problem yourself! Yes, you could post this on the
twobitreader github.
