### ISSUE TITLE
Specific target sequence can reproducibly crash the site

### ISSUE THREAD

**Issue by aaronmck** [maximilianh/crisporWebsite#7]
First, just wanted to say this is a great tool! I've been working on a side-project of mine, a command line tool for this kind of thing (see github.com/aaronmck/DeepFry). I was looking at some of my negative Moreno-Mateos hits for comparison, and putting the following sequence (my most negative hit) into CRISPOR crashed the site with a '<type 'exceptions.KeyError'>' error:

AAAAATTTTTAAAAATTAGCTGG (with human NGG)

A screenshot is attached. Anyway, just wanted to give you a heads up, and thanks again for aggregating all these scoring methods, it's been incredibly useful!

![crash](https://user-images.githubusercontent.com/1264127/27093568-16dc9e50-501c-11e7-94fe-d1174020074f.jpg)

**Comment by maximilianh** [comment]
Hi Aaron, many thanks, great bug report! <CN0> appeared in the 1000 genomes VCF file, no idea what this is supposed to mean as an allele description. I'm just skipping it now.

After the last commit, it's working now, see http://tefor.net/crispor/crispor.py?batchId=VtSvTZpkb8fMjqA5pge7
